# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check1
        run: |
          echo ("CMAKE_ARG1=-DCMAKE_BUILD_TYPE=Release") >> $env:GITHUB_ENV
          echo ("CMAKE_ARG2=-DCMAKE_INSTALL_PREFIX=krpc-install") >> $env:GITHUB_ENV
          echo ("CMAKE_ARG3=-DASIO_INCLUDE_DIR=" + $((Get-Item .).FullName) + "/asio-1.22.1/include") >> $env:GITHUB_ENV
          echo ("CMAKE_ARG4=-DProtobuf_INCLUDE_DIR=" + $((Get-Item .).FullName) + "/protobuf/include") >> $env:GITHUB_ENV 
          echo ("CMAKE_ARG5=-DProtobuf_LIBRARY_RELEASE=" + $((Get-Item .).FullName) + "/protobufl/lib/libprotobuf.lib") >> $env:GITHUB_ENV 
          echo ("CMAKE_ARG6=-DProtobuf_LITE_LIBRARY_RELEASE=" + $((Get-Item .).FullName) + "/protobuf/lib/libprotobuf-lite.lib") >> $env:GITHUB_ENV 
          echo ("CMAKE_ARG7=-DProtobuf_PROTOC_EXECUTABLE=" + $((Get-Item .).FullName) + "/protobuf/bin/protoc.exe") >> $env:GITHUB_ENV 
          echo ("CMAKE_ARG8=-DProtobuf_PROTOC_LIBRARY_RELEASE=" + $((Get-Item .).FullName) + "/protobuf/lib/libprotoc.lib") >> $env:GITHUB_ENV 
          
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Check2
        env:
          BUILD_TYPE: -DCMAKE_BUILD_TYPE=Release
        run: |
          chcp 65001 #set code page to utf-8
          echo "cmake -G "NMake Makefiles" ${env:CMAKE_ARG1} ${env:CMAKE_ARG2} ${env:CMAKE_ARG3} ${env:CMAKE_ARG4} ${env:CMAKE_ARG5} ${env:CMAKE_ARG6} ${env:CMAKE_ARG7} ${env:CMAKE_ARG8} .."
          

