# Test building protobuf in Windows

name: test-run

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get compiled protobuf lib
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: protobuf.yml
          workflow_conclusion: success
          # Optional, uploaded artifact name,
          # will download all artifacts if not specified
          # and extract them in respective subdirectories
          # https://github.com/actions/download-artifact#download-all-artifacts
          name: protobuf-artifact
          path: protobuf
          
      - name: check
        run: |
          dir /A
          cd D:\a\krpc-cpp\krpc-cpp\protobuf\include
          
      - name: Get asio
        run: |
          Invoke-WebRequest "https://telkomuniversity.dl.sourceforge.net/project/asio/asio/1.22.1%20%28Stable%29/asio-1.22.1.zip" -OutFile "asio-1.22.1.zip"
          7z x asio-1.22.1.zip
          
      # In future can use our own compiled lib
      # For now just grab this one
      - name: Get the krpc lib
        run: Invoke-WebRequest "https://github.com/BenChung/krpc/releases/download/v0.4.9/krpc.1.zip" -OutFile "krpc.zip"
        
      - name: Unpack krpc lib
        run: |
          7z x krpc.zip
          7z x krpc-0.4.9.zip client/krpc-cpp-0.4.9.zip
          7z x client\krpc-cpp-0.4.9.zip
          
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Compile
        env:
          line1: -DCMAKE_BUILD_TYPE=Release 
          line2: -DCMAKE_INSTALL_PREFIX=krpc-install
          line3: -DASIO_INCLUDE_DIR=../../asio-1.22.1/include
          line4: -DProtobuf_INCLUDE_DIR=../../protobuf/include 
          line5: -DProtobuf_LIBRARY_RELEASE=../../protobufl/lib/libprotobuf.lib 
          line6: -DProtobuf_LITE_LIBRARY_RELEASE=../../protobuf/lib/libprotobuf-lite.lib 
          line7: -DProtobuf_PROTOC_EXECUTABLE=../../protobuf/bin/protoc.exe 
          line8: -DProtobuf_PROTOC_LIBRARY_RELEASE=../../protobuf/lib/libprotoc.lib 
        run: |     
          cd krpc-cpp-0.4.9
          mkdir build
          cd build
          echo "COMMAND: cmake -G "NMake Makefiles" $line1 $line2 $line3 $line4 $line5 $line6 $line7 $line8 .."
          cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=krpc-install -DASIO_INCLUDE_DIR=../../asio-1.22.1/include -DProtobuf_INCLUDE_DIR=../../protobuf/include -DProtobuf_LIBRARY_RELEASE=../../protobufl/lib/libprotobuf.lib -DProtobuf_LITE_LIBRARY_RELEASE=../../protobuf/lib/libprotobuf-lite.lib -DProtobuf_PROTOC_EXECUTABLE=../../protobuf/bin/protoc.exe -DProtobuf_PROTOC_LIBRARY_RELEASE=../../protobuf/lib/libprotoc.lib ..
          
      - uses: ilammy/msvc-dev-cmd@v1
      - name: nmake
        run: |
          cd krpc-cpp-0.4.9
          cd build
          nmake
          nmake install       
          
      - name: Copy files
        run: xcopy /E '.\krpc-cpp-0.4.9\build\krpc-install' '.\krpc-cpp-client\'
          
      - uses: actions/upload-artifact@v3
        with:
          name: krpc-cpp-client
          path: krpc-cpp-client/

