# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Check
        env:
          BUILD_TYPE: -DCMAKE_BUILD_TYPE=Release
        run: |
          echo ("WORKING_DIR=" + $((Get-Item .).FullName)) >> $env:GITHUB_ENV
          echo "BUILD TYPE: ${env:BUILD_TYPE}"
          echo "WORKING DIR: ${env:WORKING_DIR}"
